name: Build PicoPendant

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        board: [pico, pico_w, pico2, pico2_w]

    steps:
    - uses: actions/checkout@v4

    - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1.10.0
      with:
        release: '14.2.Rel1'
        path-env-var: 'PICO_TOOLCHAIN_PATH'

    - name: Checkout pico-sdk/2.1.1
      uses: actions/checkout@v4.1.1
      with:
        repository: raspberrypi/pico-sdk
        ref: 2.1.1
        path: pico-sdk
        
    - name: Checkout pico-sdk submodules
      working-directory: ${{github.workspace}}/pico-sdk
      run: git submodule update --init
      shell: bash

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DPICO_BOARD=${{ matrix.board }}
        -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} 

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.strings.outputs.build-output-dir }}/*.uf2
        token: secrets.FGT_RELEASE
